import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.css";

import { AuthProvider } from "@/context/Auth.context";
import { Navbar } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const staticLinks = [
  {
    targer: "Home",
    route: "/"
  },
  {
    targer: "Tienda",
    route: "/tienda"
  },
  {
    targer: "Admin",
    route: "/admin"
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        
        <Navbar brand={"Rincon Curly"} staticLinks={staticLinks} />

        {children}
      </AuthProvider>
      </body>
    </html>
  );
}
