import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/globals.css";

import { AuthProvider } from "@/context/Auth.context";


export const metadata = {
  title: "Rincon Curly",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        {children}
      </AuthProvider>
      </body>
    </html>
  );
}
